name: Bug Report
description: File a bug report
title: "[Issue]: "
labels: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: webui
    attributes:
      label: Webui
      description: Which webui are you using?
      options:
        - Automatic1111's webui
        - Vlad's fork webui (SD.Next)
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Something else (please specify)
      validations:
        required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional info
      description: Please provide any additional information you think might be relevant.
      placeholder: ...
      value: "A bug happened!"
    validations:
      required: false
  - type: textarea
    id: browser-logs
    attributes:
      label: Relevant browser log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: webui-logs
    attributes:
      label: Relevant log output from the webui
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Before submitting this issue, please make sure you've done the following
      options:
        - label: I have searched the issues to make sure this is not a duplicate
          required: true
        - label: Webui is up to date
          required: true
        - label: Cozy-Nest is up to date
          required: true
        - label: All my extensions are up to date
          required: true